version: '3.9'

services:
  postgres:
    container_name: nodejs_service_postgres
    build:
      context: .
      dockerfile: ./database/Dockerfile
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nodejs_service_postgres_volume
