version: '3.9'

services:
  app:
    container_name: nodejs_service_application
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - custom_network

  postgres:
    container_name: nodejs_service_postgres
    build:
      context: .
      dockerfile: ./database/Dockerfile
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - custom_network

volumes:
  postgres:
    name: nodejs_service_db_volume
  app:
    name: nodejs_service_app_volume

networks:
  custom_network:
    external: false
    driver: bridge
